### ISSUE TITLE
Properly handle sheet names length.

### ISSUE THREAD

**Issue by alexandre-lecoq** [alexandre-lecoq/QueryMultiDb#6]
# Reproduction steps #
* Uses QueryMultiDb to generate an excel file with the sheet name "_Test0123456789Test0123456789Test0123456789_".
* Open the file with excel.

# Observed #
* Excel complains about an issue in `workbook.xml`.

# Expected #
* Excel opens the generated file gracefully.

# How to fix #
* Sheet names should be limited to 31 characters maximum as excel does not allow more.
  * Limited to 31 characters in excel (MS office Professional Plus 2019 Version 1906 (Build 11727.20244)

**Comment by skimforteau** [comment]
In my version of excel (MS Office 365 ProPlus Version 1808 Build 10730.20348), sheet names are limited 32 characters.

**Comment by alexandre-lecoq** [comment]
Fixed in 4a2a77ea2f16cc958de3275ed4adf1ecd6426207
